# 系统配置
system:
  password:
    hashIterations: 2
  upload:
    template: D://upload/template/
  # cxf webservice上下文配置
  cxfservlet: /ws/*
  # cross 跨域配置 filetr实现
  cross: 
    allowedOrigins: http://27.223.85.2:9527,http://27.223.85.2:9528,http://10.19.1.80:9527,http://localhost:9527,http://127.0.0.1:9527,http://10.19.1.138:9527
  swagger2:
    page:
      title: bootEasyFrame swagger
      author: frank
      url: XXX
      email: 1184394504@qq.com
      description: bootEasyFrame swagger
      version: 1.0
#webservice发布上下文
cxfservlet: /ws/*
spring:
  profiles:
    active: @env@
  #验证码 localhost:9999/kaptcha
  kaptcha:
    enable: true
    properties:
      kaptcha.border.color: 105,179,90
      kaptcha.textproducer.font.color: blue
      kaptcha.image.width: "125"
      kaptcha.image.height: "45"
      kaptcha.textproducer.font.size: "45"
      kaptcha.session.key: KAPTCHA_SESSION_KEY
      kaptcha.textproducer.char.length: "4"
      kaptcha.textproducer.font.names: 宋体,楷体,微软雅黑
    suffix: suffix
  http:
    encoding:
      force: true
  aop:
    proxy-target-class: true
  cache:
    ehcache:
      config: classpath:ehcache.xml
server:
  port: 9999
  tomcat:
    uri-encoding: UTF-8
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.frank.boot.domain
logging:
  file: /home/logs/newErp.log
  level: info
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'


